export const INGREDIENTS_SET = "INGREDIENTS_SET";

export const INGREDIENT_INCREASE_COUNTER = "INGREDIENT_INCREASE_COUNTER";

export const INGREDIENT_DECREASE_COUNTER = "INGREDIENT_DECREASE_COUNTER";
